//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BearFTP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BearFTP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;PortDef&quot;: 21,
        ///  &quot;PortPasv&quot;: 21,
        ///  &quot;Hostname&quot;: &quot;127.0.0.1&quot;,
        ///  &quot;Banner&quot;: &quot;My very own FTP server located at %host%&quot;,
        ///  &quot;Token&quot;: &quot;&quot;,
        ///  &quot;Report&quot;: true,
        ///  &quot;Ban&quot;: true,
        ///  &quot;PunishScans&quot;: true,
        ///  &quot;AllowAnonymous&quot;: false,
        ///  &quot;PerIPLogs&quot;: false,
        ///  &quot;AnonStat&quot;: true,
        ///  &quot;ConsoleLogging&quot;: true,
        ///  &quot;ActiveMode&quot;: true,
        ///  &quot;Max_PerSecond&quot;: 5,
        ///  &quot;Max_Total&quot;: 6,
        ///  &quot;BanLength&quot;: 3600,
        ///  &quot;MaxErrors&quot;: 6,
        ///  &quot;BufferSize&quot;: 8192,
        ///  &quot;MaxThreads&quot;: 50,
        ///  &quot;Files&quot;: [
        ///  {
        ///    &quot;Name&quot;: &quot;readme.txt&quot;,
        ///    &quot;Content&quot;: &quot;H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfigFile {
            get {
                return ResourceManager.GetString("ConfigFile", resourceCulture);
            }
        }
    }
}
